### PR TITLE
Fixing issues with .wait method and updating build version

### PR DESCRIPTION
**Pull request by nick-aspinall-mixrad**

### CODE REVIEW

**Comment by nick-aspinall-mixrad** [comment]
@kelveden Would you mind reviewing this PR please?

**Comment by kelveden** [comment]
Not sure why this is required. The call to `wait` should occur after the `@response` has been initialised in `respond_with`. Something like this:

```ruby
vanilli.stub(vanilli.on_get("/some/url").respond_with(...).wait(1000))
```

**Comment by kelveden** [comment]
Reopening as after seeing an example of the syntactic sugar that being able to say `wait` before `respond_with` I'm converted.

**Comment by nick-aspinall-mixrad** [comment]
Time well spent then :) Thanks @kelveden

**Pull request merged**
